---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
resources:
  - ./pki/instana-issuer.yaml
  - ./datastores/namespace.yaml
  - ./datastores/elasticsearch.yaml
  - ./datastores/kafka.yaml
  - ./datastores/zookeeper-application.yaml
  - ./datastores/clickhouse-application.yaml
  - ./datastores/cassandra-spans.yaml
  - ./datastores/cassandra-profiles.yaml
  - ./datastores/cassandra-metrics.yaml
  - ./datastores/cassandra-state.yaml
  - ./datastores/zookeeper-kafka.yaml
  - ./datastores/users-xml.yaml
  - ./datastores/cockroachdb.yaml
  - ./core/instana-registry.yaml
  #- ./core/instana-certificate.yaml
  #- ./units/instana-registry.enc.yaml