---
apiVersion: v1
kind: Secret
metadata:
  name: instana-registry
  namespace: instana-core
type: Opaque
stringData:
    registryConfiguration: ${registryConfiguration}
# stringData: 
#   .dockerconfigjson: |
#     ${registryConfiguration}