---
apiVersion: v1
kind: Secret
metadata:
  name: instana-registry
  namespace: instana-core
type: Opaque
data:
    registryConfiguration: ${data.registryConfiguration}
# stringData: 
#   .dockerconfigjson: |
#     ${registryConfiguration}