---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
resources:
  - region-config.yaml
  - region-secrets.enc.yaml
  - base.yaml
  - instana-core.enc.yaml
  - instana-core.yaml
  - pvc.yaml