---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-instana-admin
  namespace: datastores
type: kubernetes.io/basic-auth
stringData:
  username: instana
  password: ${datastorePassword}
  roles: superuser
