---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/install
  targetNamespace: flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system