apiVersion: v1
kind: Secret
metadata:
    name: instana-registry
    namespace: instana-operator
type: kubernetes.io/dockerconfigjson
stringData: 
  .dockerconfigjson: |
    {"auths": {"https://containers.instana.io": {"username": "${registryUsername}", "password": "${registryPassword}","email": "any@notused.com","auth":"${registryAuth}"}}}
